<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="1" total="6" passed="0" failed="1" skipped="4">
  <reporter-output>
  </reporter-output>
  <suite started-at="2023-05-20T21:23:08 EDT" name="Default suite" finished-at="2023-05-20T21:23:43 EDT" duration-ms="35195">
    <groups>
    </groups>
    <test started-at="2023-05-20T21:23:08 EDT" name="Default test" finished-at="2023-05-20T21:23:43 EDT" duration-ms="35195">
      <class name="testNGbasics.TestNGAnnotationsUnderstanding">
        <test-method is-config="true" signature="loadApp()[pri:0, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725]" started-at="2023-05-20T21:23:08 EDT" name="loadApp" finished-at="2023-05-20T21:23:35 EDT" duration-ms="27822" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loadApp -->
        <test-method is-config="true" signature="homePageCheck()[pri:0, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725]" started-at="2023-05-20T21:23:35 EDT" name="homePageCheck" finished-at="2023-05-20T21:23:40 EDT" duration-ms="4408" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePageCheck -->
        <test-method signature="homePageTest()[pri:0, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725]" started-at="2023-05-20T21:23:40 EDT" name="homePageTest" finished-at="2023-05-20T21:23:40 EDT" duration-ms="330" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [http://www.amazon.com/] but found [https://www.amazon.com/]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [http://www.amazon.com/] but found [https://www.amazon.com/]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at org.testng.Assert.assertEquals(Assert.java:639)
at testNGbasics.TestNGAnnotationsUnderstanding.homePageTest(TestNGAnnotationsUnderstanding.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:567)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- homePageTest -->
        <test-method signature="positiveSearchFunctionalityUsingEnterKey()[pri:1, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725]" started-at="2023-05-20T21:23:40 EDT" name="positiveSearchFunctionalityUsingEnterKey" finished-at="2023-05-20T21:23:40 EDT" depends-on-methods="testNGbasics.TestNGAnnotationsUnderstanding.homePageTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGAnnotationsUnderstanding.positiveSearchFunctionalityUsingEnterKey()[pri:1, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGAnnotationsUnderstanding.positiveSearchFunctionalityUsingEnterKey()[pri:1, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveSearchFunctionalityUsingEnterKey -->
        <test-method signature="negativeSearchFunctionalityUsingSearchBtn()[pri:2, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725]" started-at="2023-05-20T21:23:40 EDT" name="negativeSearchFunctionalityUsingSearchBtn" finished-at="2023-05-20T21:23:40 EDT" depends-on-methods="testNGbasics.TestNGAnnotationsUnderstanding.homePageTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGAnnotationsUnderstanding.negativeSearchFunctionalityUsingSearchBtn()[pri:2, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGAnnotationsUnderstanding.negativeSearchFunctionalityUsingSearchBtn()[pri:2, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeSearchFunctionalityUsingSearchBtn -->
        <test-method signature="negativeSearchFunctionalityUsingEnterKey()[pri:3, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725]" started-at="2023-05-20T21:23:40 EDT" name="negativeSearchFunctionalityUsingEnterKey" finished-at="2023-05-20T21:23:40 EDT" depends-on-methods="testNGbasics.TestNGAnnotationsUnderstanding.homePageTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGAnnotationsUnderstanding.negativeSearchFunctionalityUsingEnterKey()[pri:3, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGAnnotationsUnderstanding.negativeSearchFunctionalityUsingEnterKey()[pri:3, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- negativeSearchFunctionalityUsingEnterKey -->
        <test-method signature="positiveSearchFunctionalityUsingSearchBtn()[pri:4, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725]" started-at="2023-05-20T21:23:40 EDT" name="positiveSearchFunctionalityUsingSearchBtn" finished-at="2023-05-20T21:23:40 EDT" depends-on-methods="testNGbasics.TestNGAnnotationsUnderstanding.homePageTest" duration-ms="0" status="SKIP">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestNGAnnotationsUnderstanding.positiveSearchFunctionalityUsingSearchBtn()[pri:4, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725] depends on not successfully finished methods]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestNGAnnotationsUnderstanding.positiveSearchFunctionalityUsingSearchBtn()[pri:4, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725] depends on not successfully finished methods
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:102)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- positiveSearchFunctionalityUsingSearchBtn -->
        <test-method is-config="true" signature="closeApp()[pri:0, instance:testNGbasics.TestNGAnnotationsUnderstanding@58695725]" started-at="2023-05-20T21:23:40 EDT" name="closeApp" finished-at="2023-05-20T21:23:43 EDT" duration-ms="2438" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeApp -->
      </class> <!-- testNGbasics.TestNGAnnotationsUnderstanding -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
